### ISSUE TITLE
Interactive communication channel

### ISSUE THREAD

**Issue by gnzlbg** [rust-cuda/wg#3]
We are already enough people to create an "official" working group. There are a couple of things to do before an announcement, which might attract even more people to work together, but I think that the first thing is to find a place to interactively be able to communicate. 

## Expressed preferences

These are the expressed preferences for an interactive communication tool: 

@gnzlbg -> preferably zulip, but discord would work too
@denzp ->  slack for work so its open most of the time, but zulip would work too
@bheisler -> preferably slack/discord, but zulip could work too,
@vadixidav ->
@termoshtt -> preberable slack, but discord/zulip could work too

Would be cool if you could chime in, even if just to say "no strong preference".

## Requirements and candidates

* Requirements: 

   * it has to work for us, since we will be using it most of the time

   * low barrier of entry: it has to be a tool that's already in use by the rust-lang working groups, this makes our "channel" more easy discoverable for new users, beginners, new contributors, core team members, etc. 

   * goodies: good web interface, threaded conversations like Zulip, or we'll need to have multiple channels like in Discord / IRC, easy to export meeting minutes, easy to link github issues/PRs, embed Rust code, etc. 

* Candidates: the rust-lang organization uses IRC, Discord, and Zulip - IRC is probably out, since we can't easily share code / link to github / etc. without IRC bots. So that cuts it down to Discord and Zulip.

So what's your preference, if any? 

Also, keep in mind that the tool has to work for us, we can try Discord, or Zulip, and if it doesn't work, we can move to something else. This is completely up to us.

**Comment by gnzlbg** [comment]
My personal preference is Zulip. It's currently used by the wg-unsafe-code-guidelines, wg-nll, wg-secure-code, and wg-traits. I hate having multiple tools open, and at one point I had IRC, Discord, and Zulip open, but I've mostly cutted on IRC and Discord because I found Zulip to just be nicer for these kind of use cases - I still join Discord occasionally to interact with the wg that use it, and I will keep it open all the time if that's what we choose.

There are pros and cons to zulip:

* niko matsakis on the pros/const of zulip: https://internals.rust-lang.org/t/exploring-new-communication-channels/7859/70
* varkor on the cons of zulip: https://internals.rust-lang.org/t/zulip-shortcomings/8454

For me the big pro is that all conversations are threaded, so you always know what people are talking about, be it a github issue, a topic, a meeting, etc. And you can filter the chat by conversation and follow along even though there might be multiple conversations going on at the same time. This makes it trivial to e.g. collect meeting minutes.

**Comment by termoshtt** [comment]
I usually use slack, but discord/zulip would work.

**Comment by denzp** [comment]
I tried Zulip today and enjoyed the threads conversation model. Alternatively, I use Slack for work and it's open most of the time, so it should work for me as well.

**Comment by gnzlbg** [comment]
There appears to be a strong preference for Slack. There does not seem to be an official rust-lang channel/organization, so I worry that we might have problem attracting new people and interacting with the rest of the community if we host it there (e.g. sometimes it is useful to just ping somebody from the compiler team or the libs team). 

Is this worry unfounded ? 

---

* Also, does slack still require a paid account to have infinite scroll-back? Back when I used slack it used to have this limitation, but maybe this has changed?

**Comment by denzp** [comment]
@gnzlbg I think your concerns are correct. Interaction with the rest of the community in the best case will be limited. TIL there is no easy way to make a "public" workspace in Slack, only workarounds with [automatic inviting](https://github.com/rauchg/slackin).

And yes, free accounts in Slack are subjected to message history limit. So I think Slack is not really an option for us...

I would say that now I prefer Zulip, but I'm also open to any other platform as well.

Regards to Zulip and Discord comparison (never really used both before) it feels to me, that Discord Rust community is bigger / more active. The argument might be a game changer if we want to get more feedback from community.

**Comment by gnzlbg** [comment]
> Regards to Zulip and Discord comparison (never really used both before) it feels to me, that Discord Rust community is bigger / more active. The argument might be a game changer if we want to get more feedback from community.

You are completely right! I just checked and there are ~400 Discord users. Zulip does not provide an exact count AFAICT, but quickly counting them it appears to have 100-150 users. 

> I would say that now I prefer Zulip, but I'm also open to any other platform as well.

I still prefer Zulip for collaborating, talking about implementation-related work, etc. But as a channel for beginner and new users to ask questions, Discord might be a better place. 

---

The trade-offs are unclear, so I've done the following: I've asked for a `wg-cuda` channel in both Zulip and Discord. We can start using Zulip to collaborate, and those of us who will hang on Discord anyways, can also use the wg-cuda channel to give us some visibility, and so that we can answer beginner questions if any. 

We can decide at a later time whether we move exclusively to Zulip, or to Discord, or just keep both. If we decide at a later time to move to Discord, I'll ask for a "group of channels" instead, so that we can keep conversations related to different topics (implementation, meetings, questions, etc.) separated.

**Comment by gnzlbg** [comment]
So I managed to contact the people in charge, and until the edition is released the policy is to not charter any more working groups. After the edition, the plan is to first create a process about how to create working groups, and decide on what to work next for the next edition. 

What does this mean for us? For now, we won't have a channel in the official Discord / Tulip rust-lang organizations, nor a tag on Discord, etc. 

It doesn't mean that we can't work together on solving issues that are important for us. 

I've created a Zulip organization for rust cuda, please join: https://rust-cuda.zulipchat.com 

If we feel like we should use Discord, we can just create a Discord organization in the future and move there.

**Comment by Dylan-DPC-zz** [comment]
@gnzlbg can't join. people need an invitation to join the zulip channel

**Comment by gnzlbg** [comment]
I’ve set the Zulip channel to no invite required, it should work now.
